### ISSUE TITLE
SwiftEmitModule normal arm64

### ISSUE THREAD

**Issue by orelvis15** [eye-dee/kotlin-2.0-multiplatform-cocoapods#3]
Hello, good afternoon, I am having problems compiling my project, I cloned this and tried to compile it but it gives me this error

```
The following build commands failed:
  SwiftEmitModule normal arm64 Emitting\ module\ for\ K2Test (in target 'iosApp' from project 'iosApp')
(1 failure)

..kotlin-2.0-multiplatform-cocoapods/iosApp/iosApp/ContentView.swift:3:8: error: no such module 'ComposeApp'
import ComposeApp
       ^
```

I'm on an M3 mac.

Do you have any idea what could be happening?
Thanks in advance.

**Comment by eye-dee** [comment]
Hello

Thanks for your question, I think I messed up lowercased `composeApp` and uppercase `ComposeApp` in different place of the application

It works on my end tho

**Comment by orelvis15** [comment]
If that was exactly what it was, I had it in lowercase that's why I couldn't find the module. Thank you very much for responding so quickly!
